/**
 * figmaData — extracted from the live Figma libraries, not written by hand.
 *
 * GENERATED by scripts/figma-tokens/reduce.py. Do not edit; re-run the script.
 *
 * Every count, hex, alias and variant name in this file was read out of the
 * published files and reduced by script. Nothing here is illustrative. Where a
 * name is misspelled — `Aleart`, `Interective`, `Secondery`, `Tercery`,
 * `Netural` — it is misspelled in the library, and it is reproduced verbatim,
 * because a token name is an API and this case study is about what the system
 * actually is.
 *
 * Source files:
 *   Tokens            · V2qdpU2nsj5VnWIN2EJXkH
 *   Components        · AUdlDvbPYr1eMPM6SM7IPT
 *   IDP 1 Foundations · e9Y6cM1w7sQKrUifpOrPVZ
 *   IDP 2 Core        · nJkQ5zrJD6srYJLBnnfnIg
 *
 * Reduced from documentation frames dated 10/07/2025.
 */

export type Resolved = { alias: string | null; value: string };
export type ThemeRow = { token: string; Blue: Resolved; Orange: Resolved };
export type ModeRow = { token: string; onLight: Resolved; onDark: Resolved };

/** The five variable collections, with the mode axis each one owns. */
export const COLLECTIONS = [
  { name: "_global-colors", label: "Primitives · colour", count: 211, modes: ["Mode 1"], note: "Raw hexes. No opinion about where they are used." },
  { name: "_global-sizes", label: "Primitives · size", count: 50, modes: ["Mode 1"], note: "Raw numbers on a 2px grid. No opinion about what they measure." },
  { name: "global-extra", label: "Aliased scales", count: 68, modes: ["Mode 1"], note: "radius, spacing, borderWidth, iconSize, opacity, elevation — named steps pointing at size primitives." },
  { name: "Theme", label: "Brand", count: 46, modes: ["Blue", "Orange"], note: "The brand-owned roles. Two modes, one per brand." },
  { name: "Mode", label: "Appearance", count: 251, modes: ["onLight", "onDark"], note: "What components actually bind to. Two modes, light and dark." },
] as const;

/** All primitive colour families, every step, exactly as published. */
export const PALETTE: { family: string; steps: { step: string; hex: string }[] }[] = [
  { family: "Aleart/Error", steps: [{ step: "50", hex: "#FFE9E9" }, { step: "100", hex: "#FEBABA" }, { step: "200", hex: "#FE9999" }, { step: "300", hex: "#FE6A6A" }, { step: "400", hex: "#FD4D4D" }, { step: "500", hex: "#FD2121" }, { step: "600", hex: "#E61E1E" }, { step: "700", hex: "#B41717" }, { step: "800", hex: "#8B1212" }, { step: "900", hex: "#6A0E0E" }, { step: "1000", hex: "#570C0C" }, { step: "1100", hex: "#420909" }, { step: "1200", hex: "#2E0606" }, { step: "a50", hex: "#FD2121 @0%" }, { step: "a100", hex: "#FD2121 @18%" }, { step: "a150", hex: "#FD2121 @24%" }, { step: "a200", hex: "#FD2121 @32%" }, ] },
  { family: "Aleart/Success", steps: [{ step: "50", hex: "#E9FFEA" }, { step: "100", hex: "#BAFEBD" }, { step: "200", hex: "#99FE9D" }, { step: "300", hex: "#4DFD55" }, { step: "400", hex: "#4DFD55" }, { step: "500", hex: "#21FD2A" }, { step: "600", hex: "#1EE626" }, { step: "700", hex: "#17B41E" }, { step: "800", hex: "#128B17" }, { step: "900", hex: "#0E6A12" }, { step: "1000", hex: "#0B520E" }, { step: "1100", hex: "#093D0B" }, { step: "1200", hex: "#052406" }, { step: "a50", hex: "#21FD2A @9%" }, { step: "a100", hex: "#21FD2A @18%" }, { step: "a150", hex: "#21FD2A @24%" }, { step: "a200", hex: "#21FD2A @32%" }, ] },
  { family: "Aleart/Warning", steps: [{ step: "50", hex: "#FFF3E9" }, { step: "100", hex: "#FEDBBA" }, { step: "200", hex: "#FEC999" }, { step: "300", hex: "#FEB16A" }, { step: "400", hex: "#FDA14D" }, { step: "500", hex: "#FD8A21" }, { step: "600", hex: "#E67E1E" }, { step: "700", hex: "#B46217" }, { step: "800", hex: "#8B4C12" }, { step: "900", hex: "#6A3A0E" }, { step: "1000", hex: "#522D0C" }, { step: "1100", hex: "#3D2209" }, { step: "1200", hex: "#291706" }, { step: "a50", hex: "#FD8A21 @0%" }, { step: "a100", hex: "#FD8A21 @18%" }, { step: "a150", hex: "#FD8A21 @24%" }, { step: "a200", hex: "#FD8A21 @32%" }, ] },
  { family: "Extras/Blue", steps: [{ step: "50", hex: "#EAF7FE" }, { step: "100", hex: "#BEE6FB" }, { step: "200", hex: "#9EDAF9" }, { step: "300", hex: "#72C9F6" }, { step: "400", hex: "#56BEF4" }, { step: "500", hex: "#2CAEF1" }, { step: "600", hex: "#109DE5" }, { step: "700", hex: "#1F7CAB" }, { step: "800", hex: "#186085" }, { step: "900", hex: "#124965" }, { step: "1000", hex: "#0F384C" }, { step: "1100", hex: "#0A2533" }, { step: "1200", hex: "#051319" }, { step: "a50", hex: "#2CAEF1 @0%" }, { step: "a100", hex: "#2CAEF1 @18%" }, { step: "a150", hex: "#2CAEF1 @24%" }, { step: "a200", hex: "#2CAEF1 @32%" }, ] },
  { family: "Extras/Emerald", steps: [{ step: "50", hex: "#F0FAF4" }, { step: "100", hex: "#D0F0DE" }, { step: "200", hex: "#AFE9C8" }, { step: "300", hex: "#8DE2B1" }, { step: "400", hex: "#6BDB9A" }, { step: "500", hex: "#49D584" }, { step: "600", hex: "#2FC66F" }, { step: "700", hex: "#34975E" }, { step: "800", hex: "#287549" }, { step: "900", hex: "#1F5937" }, { step: "1000", hex: "#1C4C30" }, { step: "1100", hex: "#174028" }, { step: "1200", hex: "#123320" }, { step: "a50", hex: "#49D584 @0%" }, { step: "a100", hex: "#49D584 @18%" }, { step: "a150", hex: "#49D584 @24%" }, { step: "a200", hex: "#49D584 @32%" }, ] },
  { family: "Extras/Purple", steps: [{ step: "50", hex: "#FBEDF9" }, { step: "100", hex: "#F1C7EC" }, { step: "200", hex: "#EBACE3" }, { step: "300", hex: "#E286D7" }, { step: "400", hex: "#DC6FCF" }, { step: "500", hex: "#D34BC3" }, { step: "600", hex: "#C044B1" }, { step: "700", hex: "#96358A" }, { step: "800", hex: "#74296B" }, { step: "900", hex: "#592052" }, { step: "1000", hex: "#471B42" }, { step: "1100", hex: "#381534" }, { step: "1200", hex: "#2E112A" }, { step: "a50", hex: "#D34BC3 @9%" }, { step: "a100", hex: "#D34BC3 @18%" }, { step: "a150", hex: "#D34BC3 @24%" }, { step: "a200", hex: "#D34BC3 @32%" }, ] },
  { family: "Extras/Yellow", steps: [{ step: "50", hex: "#FFF3E9" }, { step: "100", hex: "#FEDBBA" }, { step: "200", hex: "#FEC999" }, { step: "300", hex: "#FEB16A" }, { step: "400", hex: "#FDA14D" }, { step: "500", hex: "#FD8A21" }, { step: "600", hex: "#E67E1E" }, { step: "700", hex: "#B46217" }, { step: "800", hex: "#8B4C12" }, { step: "900", hex: "#6A3A0E" }, { step: "1000", hex: "#522D0C" }, { step: "1100", hex: "#3D2209" }, { step: "1200", hex: "#291706" }, { step: "a50", hex: "#FD8A21 @0%" }, { step: "a100", hex: "#FD8A21 @18%" }, { step: "a150", hex: "#FD8A21 @24%" }, { step: "a200", hex: "#FD8A21 @32%" }, ] },
  { family: "Product/Blue", steps: [{ step: "50", hex: "#E6EEFA" }, { step: "100", hex: "#B0C9EF" }, { step: "200", hex: "#8AAFE8" }, { step: "300", hex: "#548BDD" }, { step: "400", hex: "#3375D6" }, { step: "500", hex: "#0052CC" }, { step: "600", hex: "#004BBA" }, { step: "700", hex: "#003A91" }, { step: "800", hex: "#002D70" }, { step: "900", hex: "#002256" }, { step: "1000", hex: "#001C47" }, { step: "1100", hex: "#001433" }, { step: "1200", hex: "#001029" }, { step: "a50", hex: "#0052CC @9%" }, { step: "a100", hex: "#0052CC @18%" }, { step: "a150", hex: "#0052CC @24%" }, { step: "a200", hex: "#0052CC @32%" }, ] },
  { family: "Product/Orange", steps: [{ step: "50", hex: "#FDEEE9" }, { step: "100", hex: "#F9CABB" }, { step: "200", hex: "#F6B09A" }, { step: "300", hex: "#F28C6C" }, { step: "400", hex: "#EF7650" }, { step: "500", hex: "#EB5424" }, { step: "600", hex: "#D64C21" }, { step: "700", hex: "#A73C1A" }, { step: "800", hex: "#812E14" }, { step: "900", hex: "#63230F" }, { step: "1000", hex: "#401508" }, { step: "1100", hex: "#2E0F06" }, { step: "1200", hex: "#240C05" }, { step: "a50", hex: "#EB5424 @9%" }, { step: "a100", hex: "#EB5424 @18%" }, { step: "a150", hex: "#EB5424 @24%" }, { step: "a200", hex: "#EB5424 @32%" }, ] },
  { family: "neutral/BlueGray", steps: [{ step: "0", hex: "#FFFFFF" }, { step: "50", hex: "#F1F4F6" }, { step: "100", hex: "#D4DCE4" }, { step: "200", hex: "#BFCBD7" }, { step: "300", hex: "#A2B3C5" }, { step: "400", hex: "#90A5BA" }, { step: "500", hex: "#748EA9" }, { step: "600", hex: "#6A819A" }, { step: "700", hex: "#526578" }, { step: "800", hex: "#404E5D" }, { step: "900", hex: "#313C47" }, { step: "1000", hex: "#232B33" }, { step: "1100", hex: "#1C2229" }, { step: "1200", hex: "#151A1F" }, { step: "a25", hex: "#748EA9 @6%" }, { step: "a50", hex: "#748EA9 @9%" }, { step: "a75", hex: "#748EA9 @12%" }, { step: "a100", hex: "#748EA9 @18%" }, { step: "a200", hex: "#748EA9 @32%" }, { step: "a400", hex: "#748EA9 @64%" }, ] },
  { family: "neutral/ashGray", steps: [{ step: "0", hex: "#FFFFFF" }, { step: "50", hex: "#F3F4F5" }, { step: "100", hex: "#DADCDE" }, { step: "200", hex: "#C8CBCF" }, { step: "300", hex: "#AFB3B9" }, { step: "400", hex: "#A0A4AB" }, { step: "500", hex: "#888D96" }, { step: "600", hex: "#7C8089" }, { step: "700", hex: "#61646B" }, { step: "800", hex: "#4B4E53" }, { step: "900", hex: "#393B3F" }, { step: "1000", hex: "#2E3033" }, { step: "1100", hex: "#232426" }, { step: "1200", hex: "#171819" }, { step: "a25", hex: "#888D96 @6%" }, { step: "a50", hex: "#888D96 @9%" }, { step: "a75", hex: "Total variables: 261" }, { step: "a100", hex: "#888D96 @18%" }, { step: "a200", hex: "#888D96 @32%" }, { step: "a400", hex: "#888D96 @32%" }, ] },
];

/** The Theme collection in full — brand roles across both brands. */
export const THEME_ROWS: ThemeRow[] = [
  { token: "interactive/background/primary/Dark/default", Blue: { alias: "_global-colors/Product/Blue/400", value: "#3375D6" }, Orange: { alias: "_global-colors/Product/Orange/400", value: "#EF7650" } },
  { token: "interactive/background/primary/Dark/disabled", Blue: { alias: "_global-colors/Product/Blue/a100", value: "#0052CC @18%" }, Orange: { alias: "_global-colors/Product/Orange/a100", value: "#EB5424 @18%" } },
  { token: "interactive/background/primary/Dark/faded", Blue: { alias: "_global-colors/Product/Blue/a150", value: "#0052CC @24%" }, Orange: { alias: "_global-colors/Product/Orange/a150", value: "#EB5424 @24%" } },
  { token: "interactive/background/primary/Dark/fadedHighlighted", Blue: { alias: "_global-colors/Product/Blue/a200", value: "#0052CC @32%" }, Orange: { alias: "_global-colors/Product/Orange/a200", value: "#EB5424 @32%" } },
  { token: "interactive/background/primary/Dark/highlighted", Blue: { alias: "_global-colors/Product/Blue/300", value: "#548BDD" }, Orange: { alias: "_global-colors/Product/Orange/300", value: "#F28C6C" } },
  { token: "interactive/background/primary/Light/default", Blue: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" }, Orange: { alias: "_global-colors/Product/Orange/500", value: "#EB5424" } },
  { token: "interactive/background/primary/Light/disabled", Blue: { alias: "_global-colors/Product/Blue/a50", value: "#0052CC @9%" }, Orange: { alias: "_global-colors/Product/Orange/a50", value: "#EB5424 @9%" } },
  { token: "interactive/background/primary/Light/faded", Blue: { alias: "_global-colors/Product/Blue/a50", value: "#0052CC @9%" }, Orange: { alias: "_global-colors/Product/Orange/a50", value: "#EB5424 @9%" } },
  { token: "interactive/background/primary/Light/fadedHighlighted", Blue: { alias: "_global-colors/Product/Blue/a100", value: "#0052CC @18%" }, Orange: { alias: "_global-colors/Product/Orange/a100", value: "#EB5424 @18%" } },
  { token: "interactive/background/primary/Light/highlighted", Blue: { alias: "_global-colors/Product/Blue/700", value: "#003A91" }, Orange: { alias: "_global-colors/Product/Orange/700", value: "#A73C1A" } },
  { token: "interactive/border/primary/Dark/default", Blue: { alias: "_global-colors/Product/Blue/400", value: "#3375D6" }, Orange: { alias: "_global-colors/Product/Orange/400", value: "#EF7650" } },
  { token: "interactive/border/primary/Dark/disabled", Blue: { alias: "_global-colors/Product/Blue/a200", value: "#0052CC @32%" }, Orange: { alias: "_global-colors/Product/Orange/a200", value: "#EB5424 @32%" } },
  { token: "interactive/border/primary/Dark/faded", Blue: { alias: "_global-colors/Product/Blue/a150", value: "#0052CC @24%" }, Orange: { alias: "_global-colors/Product/Orange/a150", value: "#EB5424 @24%" } },
  { token: "interactive/border/primary/Dark/highlighted", Blue: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" }, Orange: { alias: "_global-colors/Product/Orange/500", value: "#EB5424" } },
  { token: "interactive/border/primary/Light/default", Blue: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" }, Orange: { alias: "_global-colors/Product/Orange/500", value: "#EB5424" } },
  { token: "interactive/border/primary/Light/disabled", Blue: { alias: "_global-colors/Product/Blue/a100", value: "#0052CC @18%" }, Orange: { alias: "_global-colors/Product/Orange/a100", value: "#EB5424 @18%" } },
  { token: "interactive/border/primary/Light/faded", Blue: { alias: "_global-colors/Product/Blue/a100", value: "#0052CC @18%" }, Orange: { alias: "_global-colors/Product/Orange/a100", value: "#EB5424 @18%" } },
  { token: "interactive/border/primary/Light/highlighted", Blue: { alias: "_global-colors/Product/Blue/700", value: "#003A91" }, Orange: { alias: "_global-colors/Product/Orange/700", value: "#A73C1A" } },
  { token: "interactive/icon/primary/Dark/disabled", Blue: { alias: "_global-colors/Product/Blue/a200", value: "#0052CC @32%" }, Orange: { alias: "_global-colors/Product/Orange/a100", value: "#EB5424 @18%" } },
  { token: "interactive/icon/primary/Dark/muted", Blue: { alias: "_global-colors/Product/Blue/600", value: "#004BBA" }, Orange: { alias: "_global-colors/Product/Orange/400", value: "#EF7650" } },
  { token: "interactive/icon/primary/Dark/normal", Blue: { alias: "_global-colors/Product/Blue/300", value: "#548BDD" }, Orange: { alias: "_global-colors/Product/Orange/600", value: "#D64C21" } },
  { token: "interactive/icon/primary/Dark/subtle", Blue: { alias: "_global-colors/Product/Blue/400", value: "#3375D6" }, Orange: { alias: "_global-colors/Product/Orange/500", value: "#EB5424" } },
  { token: "interactive/icon/primary/Light/disabled", Blue: { alias: "_global-colors/Product/Blue/a100", value: "#0052CC @18%" }, Orange: { alias: "_global-colors/Product/Orange/a100", value: "#EB5424 @18%" } },
  { token: "interactive/icon/primary/Light/muted", Blue: { alias: "_global-colors/Product/Blue/400", value: "#3375D6" }, Orange: { alias: "_global-colors/Product/Orange/400", value: "#EF7650" } },
  { token: "interactive/icon/primary/Light/normal", Blue: { alias: "_global-colors/Product/Blue/600", value: "#004BBA" }, Orange: { alias: "_global-colors/Product/Orange/600", value: "#D64C21" } },
  { token: "interactive/icon/primary/Light/subtle", Blue: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" }, Orange: { alias: "_global-colors/Product/Orange/500", value: "#EB5424" } },
  { token: "interactive/text/primary/Dark/disabled", Blue: { alias: "_global-colors/Product/Blue/a200", value: "#0052CC @32%" }, Orange: { alias: "_global-colors/Product/Orange/a100", value: "#EB5424 @18%" } },
  { token: "interactive/text/primary/Dark/muted", Blue: { alias: "_global-colors/Product/Blue/600", value: "#004BBA" }, Orange: { alias: "_global-colors/Product/Orange/400", value: "#EF7650" } },
  { token: "interactive/text/primary/Dark/normal", Blue: { alias: "_global-colors/Product/Blue/300", value: "#548BDD" }, Orange: { alias: "_global-colors/Product/Orange/600", value: "#D64C21" } },
  { token: "interactive/text/primary/Dark/subtle", Blue: { alias: "_global-colors/Product/Blue/400", value: "#3375D6" }, Orange: { alias: "_global-colors/Product/Orange/500", value: "#EB5424" } },
  { token: "interactive/text/primary/Light/disabled", Blue: { alias: "_global-colors/Product/Blue/a100", value: "#0052CC @18%" }, Orange: { alias: "_global-colors/Product/Orange/a100", value: "#EB5424 @18%" } },
  { token: "interactive/text/primary/Light/muted", Blue: { alias: "_global-colors/Product/Blue/400", value: "#3375D6" }, Orange: { alias: "_global-colors/Product/Orange/400", value: "#EF7650" } },
  { token: "interactive/text/primary/Light/normal", Blue: { alias: "_global-colors/Product/Blue/600", value: "#004BBA" }, Orange: { alias: "_global-colors/Product/Orange/600", value: "#D64C21" } },
  { token: "interactive/text/primary/Light/subtle", Blue: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" }, Orange: { alias: "_global-colors/Product/Orange/500", value: "#EB5424" } },
  { token: "surface/background/primary/Dark/intense", Blue: { alias: "_global-colors/Product/Blue/100", value: "#B0C9EF" }, Orange: { alias: "_global-colors/Product/Orange/100", value: "#F9CABB" } },
  { token: "surface/background/primary/Dark/subtle", Blue: { alias: "_global-colors/Product/Blue/a50", value: "#0052CC @9%" }, Orange: { alias: "_global-colors/Product/Orange/a50", value: "#EB5424 @9%" } },
  { token: "surface/background/primary/Light/intense", Blue: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" }, Orange: { alias: "_global-colors/Product/Orange/500", value: "#EB5424" } },
  { token: "surface/background/primary/Light/subtle", Blue: { alias: "_global-colors/Product/Blue/a50", value: "#0052CC @9%" }, Orange: { alias: "_global-colors/Product/Orange/a50", value: "#EB5424 @9%" } },
  { token: "surface/border/primary/Dark/muted", Blue: { alias: "_global-colors/Product/Blue/a100", value: "#0052CC @18%" }, Orange: { alias: "_global-colors/Product/Blue/a100", value: "#0052CC @18%" } },
  { token: "surface/border/primary/Dark/normal", Blue: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" }, Orange: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" } },
  { token: "surface/border/primary/Light/muted", Blue: { alias: "_global-colors/Product/Blue/a100", value: "#0052CC @18%" }, Orange: { alias: "_global-colors/Product/Blue/a100", value: "#0052CC @18%" } },
  { token: "surface/border/primary/Light/normal", Blue: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" }, Orange: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" } },
  { token: "surface/icon/primary/Dark/normal", Blue: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" }, Orange: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" } },
  { token: "surface/icon/primary/Light/normal", Blue: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" }, Orange: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" } },
  { token: "surface/text/primary/Dark/normal", Blue: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" }, Orange: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" } },
  { token: "surface/text/primary/Light/normal", Blue: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" }, Orange: { alias: "_global-colors/Product/Blue/500", value: "#0052CC" } },
];

/** The Mode tokens that route through Theme — the entire brand surface. */
export const ROUTED_TOKENS: ModeRow[] = [
  { token: "interactive/background/primary/default", onLight: { alias: "interactive/background/primary/Light/default", value: "#0052CC" }, onDark: { alias: "interactive/background/primary/Dark/default", value: "#3375D6" } },
  { token: "interactive/background/primary/disabled", onLight: { alias: "interactive/background/primary/Light/disabled", value: "#0052CC @9%" }, onDark: { alias: "interactive/background/primary/Dark/disabled", value: "#0052CC @18%" } },
  { token: "interactive/background/primary/faded", onLight: { alias: "interactive/background/primary/Light/faded", value: "#0052CC @9%" }, onDark: { alias: "interactive/background/primary/Dark/faded", value: "#0052CC @24%" } },
  { token: "interactive/background/primary/fadedHighlighted", onLight: { alias: "interactive/background/primary/Light/fadedHighlighted", value: "#0052CC @18%" }, onDark: { alias: "interactive/background/primary/Dark/fadedHighlighted", value: "#0052CC @32%" } },
  { token: "interactive/background/primary/highlighted", onLight: { alias: "interactive/background/primary/Light/highlighted", value: "#003A91" }, onDark: { alias: "interactive/background/primary/Dark/highlighted", value: "#548BDD" } },
  { token: "interactive/border/primary/default", onLight: { alias: "interactive/border/primary/Light/default", value: "#0052CC" }, onDark: { alias: "interactive/border/primary/Dark/default", value: "#3375D6" } },
  { token: "interactive/border/primary/disabled", onLight: { alias: "interactive/border/primary/Light/disabled", value: "#0052CC @18%" }, onDark: { alias: "interactive/border/primary/Dark/disabled", value: "#0052CC @32%" } },
  { token: "interactive/border/primary/faded", onLight: { alias: "interactive/border/primary/Light/faded", value: "#0052CC @18%" }, onDark: { alias: "interactive/border/primary/Dark/faded", value: "#0052CC @24%" } },
  { token: "interactive/border/primary/highlighted", onLight: { alias: "interactive/border/primary/Light/highlighted", value: "#003A91" }, onDark: { alias: "interactive/border/primary/Dark/highlighted", value: "#0052CC" } },
  { token: "interactive/icon/primary/disabled", onLight: { alias: "interactive/icon/primary/Light/disabled", value: "#0052CC @18%" }, onDark: { alias: "interactive/icon/primary/Dark/disabled", value: "#0052CC @32%" } },
  { token: "interactive/icon/primary/muted", onLight: { alias: "interactive/icon/primary/Light/muted", value: "#3375D6" }, onDark: { alias: "interactive/icon/primary/Dark/muted", value: "#004BBA" } },
  { token: "interactive/icon/primary/normal", onLight: { alias: "interactive/icon/primary/Light/normal", value: "#004BBA" }, onDark: { alias: "interactive/icon/primary/Dark/normal", value: "#548BDD" } },
  { token: "interactive/icon/primary/subtle", onLight: { alias: "interactive/icon/primary/Light/subtle", value: "#0052CC" }, onDark: { alias: "interactive/icon/primary/Dark/subtle", value: "#3375D6" } },
  { token: "interactive/text/primary/disabled", onLight: { alias: "interactive/text/primary/Light/disabled", value: "#0052CC @18%" }, onDark: { alias: "interactive/text/primary/Dark/disabled", value: "#0052CC @32%" } },
  { token: "interactive/text/primary/muted", onLight: { alias: "interactive/text/primary/Light/muted", value: "#3375D6" }, onDark: { alias: "interactive/text/primary/Dark/muted", value: "#004BBA" } },
  { token: "interactive/text/primary/normal", onLight: { alias: "interactive/text/primary/Light/normal", value: "#004BBA" }, onDark: { alias: "interactive/text/primary/Dark/normal", value: "#548BDD" } },
  { token: "interactive/text/primary/subtle", onLight: { alias: "interactive/text/primary/Light/subtle", value: "#0052CC" }, onDark: { alias: "interactive/text/primary/Dark/subtle", value: "#3375D6" } },
  { token: "surface/background/primary/intense", onLight: { alias: "surface/background/primary/Light/intense", value: "#0052CC" }, onDark: { alias: "surface/background/primary/Dark/intense", value: "#B0C9EF" } },
  { token: "surface/background/primary/subtle", onLight: { alias: "surface/background/primary/Light/subtle", value: "#0052CC @9%" }, onDark: { alias: "surface/background/primary/Dark/subtle", value: "#0052CC @9%" } },
  { token: "surface/border/primary/muted", onLight: { alias: "surface/border/primary/Light/muted", value: "#0052CC @18%" }, onDark: { alias: "surface/border/primary/Dark/muted", value: "#0052CC @18%" } },
  { token: "surface/border/primary/normal", onLight: { alias: "surface/border/primary/Light/normal", value: "#0052CC" }, onDark: { alias: "surface/border/primary/Dark/normal", value: "#0052CC" } },
  { token: "surface/icon/primary/normal", onLight: { alias: "surface/icon/primary/Light/normal", value: "#0052CC" }, onDark: { alias: "surface/icon/primary/Dark/normal", value: "#0052CC" } },
  { token: "surface/text/primary/normal", onLight: { alias: "surface/text/primary/Light/normal", value: "#0052CC" }, onDark: { alias: "surface/text/primary/Dark/normal", value: "#0052CC" } },
];

/** How the 251 bindable tokens resolve. Computed, not asserted. */
export const RESOLUTION = {
  total: 251,
  routed: 23,
  direct: 222,
  raw: 6,
  rawTokens: ["elevation/_bottomSheet", "elevation/_toast", "elevation/highRaised", "elevation/lowRaised", "elevation/midRaised", "transparent"],
} as const;

/**
 * The multimapping, resolved end to end for one binding.
 *
 * A component binds ONE variable. Two independent collections then resolve it
 * against brand and appearance, so the single binding carries four values and
 * the component file contains none of them.
 */
export const CHAIN = {
  binding: "interactive/background/primary/default",
  resolutions: [
    { mode: "onLight", brand: "Blue", via: "interactive/background/primary/Light/default", primitive: "_global-colors/Product/Blue/500", hex: "#0052CC" },
    { mode: "onLight", brand: "Orange", via: "interactive/background/primary/Light/default", primitive: "_global-colors/Product/Orange/500", hex: "#EB5424" },
    { mode: "onDark", brand: "Blue", via: "interactive/background/primary/Dark/default", primitive: "_global-colors/Product/Blue/400", hex: "#3375D6" },
    { mode: "onDark", brand: "Orange", via: "interactive/background/primary/Dark/default", primitive: "_global-colors/Product/Orange/400", hex: "#EF7650" },
  ],
} as const;

/** The aliased scales — named steps pointing at size primitives. */
export const SCALES: { group: string; items: { name: string; alias: string | null; value: string }[] }[] = [
  { group: "spacing", items: [{ name: "0", alias: "_global-sizes/0px = 0rem", value: "0" }, { name: "12", alias: "_global-sizes/12px = 0-75rem", value: "12" }, { name: "16", alias: "_global-sizes/16px = 1rem", value: "16" }, { name: "2", alias: "_global-sizes/2px = 0-125rem", value: "2" }, { name: "20", alias: "_global-sizes/20px = 1-25rem", value: "20" }, { name: "24", alias: "_global-sizes/24px = 1-5rem", value: "24" }, { name: "32", alias: "_global-sizes/32px = 2rem", value: "32" }, { name: "4", alias: "_global-sizes/4px = 0-25rem", value: "4" }, { name: "40", alias: "_global-sizes/40px = 2-5rem", value: "40" }, { name: "48", alias: "_global-sizes/48px= 3rem", value: "48" }, { name: "56", alias: "_global-sizes/56px = 3-5rem", value: "56" }, { name: "8", alias: "_global-sizes/6px = 0-375rem", value: "6" }, ] },
  { group: "borderRadius", items: [{ name: "10Xl", alias: "_global-sizes/48px= 3rem", value: "48" }, { name: "2Xl", alias: "_global-sizes/20px = 1-25rem", value: "20" }, { name: "3Xl", alias: "_global-sizes/16px = 1rem", value: "16" }, { name: "4Xl", alias: "_global-sizes/24px = 1-5rem", value: "24" }, { name: "5Xl", alias: "_global-sizes/28px = 1-875rem", value: "28" }, { name: "6Xl", alias: "_global-sizes/32px = 2rem", value: "32" }, { name: "7Xl", alias: "_global-sizes/36px = 2-25rem", value: "36" }, { name: "8Xl", alias: "_global-sizes/40px = 2-5rem", value: "40" }, { name: "9Xl", alias: "_global-sizes/44px = 2-75rem", value: "44" }, { name: "Full", alias: "_global-sizes/1000px = 62-5rem", value: "1000" }, { name: "Lg", alias: "_global-sizes/12px = 0-75rem", value: "12" }, { name: "Md", alias: "_global-sizes/8px = 0-5rem", value: "8" }, { name: "None", alias: "_global-sizes/0px = 0rem", value: "0" }, { name: "Sm", alias: "_global-sizes/4px = 0-25rem", value: "4" }, { name: "Xl", alias: "_global-sizes/16px = 1rem", value: "16" }, { name: "Xs", alias: "_global-sizes/2px = 0-125rem", value: "2" }, ] },
  { group: "borderWidth", items: [{ name: "none", alias: null, value: "0" }, { name: "thick", alias: null, value: "1.5" }, { name: "thicker", alias: null, value: "2" }, { name: "thin", alias: null, value: "1" }, { name: "thinner", alias: null, value: "0.5" }, ] },
  { group: "iconSize", items: [{ name: "2Xl", alias: "_global-sizes/40px = 2-5rem", value: "40" }, { name: "Lg", alias: "_global-sizes/24px = 1-5rem", value: "24" }, { name: "Md", alias: "_global-sizes/20px = 1-25rem", value: "20" }, { name: "Sm", alias: "_global-sizes/16px = 1rem", value: "16" }, { name: "Xl", alias: "_global-sizes/32px = 2rem", value: "32" }, { name: "Xs", alias: "_global-sizes/12px = 0-75rem", value: "12" }, ] },
  { group: "opacity", items: [{ name: "0", alias: null, value: "0" }, { name: "100", alias: null, value: "100" }, { name: "12", alias: null, value: "12" }, { name: "18", alias: null, value: "18" }, { name: "24", alias: null, value: "24" }, { name: "32", alias: null, value: "32" }, { name: "48", alias: null, value: "48" }, { name: "56", alias: null, value: "56" }, { name: "64", alias: null, value: "64" }, { name: "72", alias: null, value: "72" }, { name: "80", alias: null, value: "80" }, { name: "88", alias: null, value: "88" }, { name: "9", alias: null, value: "9" }, ] },
];
